apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettools-deployment
spec:
  selector:
    matchLabels:
      app: nettools
  template:
    metadata:
      labels:
        app: nettools
    spec:
      containers:
      - name: nettools
        image: wbitt/network-multitool